server:
  port: 8080

spring:
  application:
    name: api
  cloud:
    function:
      definition: sendEvent;
    stream:
      schema-registry-client:
        endpoint: http://localhost:8081
      bindings:
        sendEvent-out-0:
          useNativeEncoding: true
          destination: events
          content-type: application/*+avro
          group: group-1
          concurrency: 3
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
      source: events-schema